version: "3.1"
services:
  dashboard:
     build: 
       context: ./app
     restart: always
     ports:
       - 8000:8000
     depends_on:
        db:
          condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432